### ISSUE TITLE
MSW - Auto Fixture Libraries for responses

### ISSUE THREAD

**Issue by NickersWeb** [citypaul/fullstack-react-tdd-example#49]
Q: Do you know of any libs that work well with msw? E.g. So that responses are not hard coded. In the past I've used efate to be a fixture builder

**Comment by citypaul** [comment]
Hey!

So the model I tend to go with is one where I create mocks using this kind of pattern: https://github.com/citypaul/fullstack-react-tdd-example/blob/main/packages/mocks/src/product.ts

The idea is that you create a function that takes an optional `overrides` argument, and you return a default set of values from the function, but override any of these values with whatever is passed into `overrides`. It works very well when combined with `Partial` in typescript.

Outside of that, the MSW team themselves provide this library: https://github.com/mswjs/data

This may be quite inline with what you're looking for, but I've never used it myself.
